name: 1時間おきのデータ自動更新

on:
  schedule:
    - cron: '0 * * * *' # 毎時0分に完全自動実行
  workflow_dispatch: # 手動でいつでも動かせるボタン

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: コードをチェックアウト
      uses: actions/checkout@v4

    - name: Pythonの準備
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 工具箱のインストール
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: データ取得スクリプトの実行
      run: python get_data.py

    - name: 更新されたデータを倉庫に保存
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add marine_data.json
        git commit -m "最新の気象データに更新" || exit 0
        git push

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: update-data
    permissions:
      pages: write
      id-token: write
    steps:
    - name: コードをチェックアウト
      uses: actions/checkout@v4
    - name: ホームページ用にデータを梱包
      uses: actions/configure-pages@v4
    - name: アップロード
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'
    - name: スマホへ最新データを直接配信
      id: deployment
      uses: actions/deploy-pages@v4
